import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

final Map<FlexScheme, String> colors = {
  FlexScheme.green: "Green",
  FlexScheme.redWine: "Red Wine",
  FlexScheme.red: "Red",
  FlexScheme.bahamaBlue: "Bahama Blue",
  FlexScheme.blumineBlue: "Blumine Blue",
  FlexScheme.shadOrange: "Shad Orange",
  FlexScheme.espresso: "Espresso",
  FlexScheme.mandyRed: "Mandy Red",
  FlexScheme.amber: "Amber",
  FlexScheme.blue: "Blue",
  FlexScheme.aquaBlue: "Aqua Blue",
  FlexScheme.barossa: "Barossa",
  FlexScheme.bigStone: "Big Stone",
  FlexScheme.blackWhite: "Black White",
  FlexScheme.blueM3: "Blue M3",
  FlexScheme.blueWhale: "Blue Whale",
  FlexScheme.brandBlue: "Brand Blue",
  FlexScheme.custom: "Custom",
  FlexScheme.cyanM3: "Cyan M3",
  FlexScheme.damask: "Damask",
  FlexScheme.deepBlue: "Deep Blue",
  FlexScheme.deepOrangeM3: "Deep Orange M3",
  FlexScheme.deepPurple: "Deep Purple",
  FlexScheme.dellGenoa: "Dell Genoa",
  FlexScheme.ebonyClay: "Ebony Clay",
  FlexScheme.flutterDash: "Flutter Dash",
  FlexScheme.gold: "Gold",
  FlexScheme.greenM3: "Green M3",
  FlexScheme.greyLaw: "Grey Law",
  FlexScheme.greys: "Greys",
  FlexScheme.hippieBlue: "Hippie Blue",
  FlexScheme.indigo: "Indigo",
  FlexScheme.indigoM3: "Indigo M3",
  FlexScheme.jungle: "Jungle",
  FlexScheme.limeM3: "Lime M3",
  FlexScheme.mallardGreen: "Mallard Green",
  FlexScheme.mango: "Mango",
  FlexScheme.material: "Material",
  FlexScheme.materialBaseline: "Material Baseline",
  FlexScheme.materialHc: "Material Hc",
  FlexScheme.money: "Money",
  FlexScheme.orangeM3: "Orange M3",
  FlexScheme.outerSpace: "Outer Space",
  FlexScheme.pinkM3: "Pink M3",
  FlexScheme.purpleBrown: "Purple Brown",
  FlexScheme.purpleM3: "Purple M3",
  FlexScheme.redM3: "Red M3",
  FlexScheme.rosewood: "Rosewood",
  FlexScheme.sakura: "Sakura",
  FlexScheme.sanJuanBlue: "San Juan Blue",
  FlexScheme.sepia: "Sepia",
  FlexScheme.shadBlue: "Shad Blue,",
  FlexScheme.shadGray: "Shad Gray",
  FlexScheme.shadGreen: "Shad Green",
  FlexScheme.shadNeutral: "Shad Neutral",
  FlexScheme.shadRed: "Shad Red",
  FlexScheme.shadRose: "Shad Rose",
  FlexScheme.shadSlate: "Shad Slate",
  FlexScheme.shadStone: "Shad Stone",
  FlexScheme.shadViolet: "Shad Violet",
  FlexScheme.shadYellow: "Shad Yellow",
  FlexScheme.shadZinc: "Shad Zinc",
  FlexScheme.shark: "Shark",
  FlexScheme.tealM3: "Teal M3",
  FlexScheme.verdunHemlock: "Verdun Hemlock",
  FlexScheme.vesuviusBurn: "Vesuvius Burn",
  FlexScheme.wasabi: "Wasabi",
  FlexScheme.yellowM3: "Yellow M3",
};
